function renderHistory(b){$("#querywindow").empty();for(var c='<table class="fancytable"><tr><th class="newsortcontrol">\u6642\u9593<div class="arrow-down"></div></th><th class="newsortcontrol">\u4eba\u54e1<div class="sorticon"></div></th><th class="newsortcontrol">\u5e74\u5ea6<div class="sorticon"></div></th><th class="newsortcontrol">\u985e\u5225<div class="sorticon"></div></th><th class="newsortcontrol">\u570b\u79d1\u6703\u4ee3\u78bc<div class="sorticon"></div></th><th class="newsortcontrol">\u5c08\u6848\u540d\u7a31<div class="sorticon"></div></th><th class="newsortcontrol">\u4e3b\u6301\u4eba<div class="sorticon"></div></th><th class="newsortcontrol">\u5e73\u53f0/\u7db2\u5740<div class="sorticon"></div></th></tr>',
a=0;a<b.length;++a)c+="<tr><td>"+b[a].timestamp+"</td>",c+="<td>"+b[a].user_id+"</td>",c+="<td>"+b[a].year+"</td>",c+="<td>"+b[a].type+"</td>",c+="<td>"+b[a].project_id+"</td>",c+="<td>"+b[a].name+"</td>",c+="<td>"+b[a].leader+"</td>",c+='<td><a href="'+b[a].url+'">'+b[a].platform+"</a></td></tr>";$("#querywindow").append(c);$("#querywindow table .newsortcontrol").click(function(){var a=$(this).index(),b=!1;0<$(this).find(".sorticon").length?($("#querywindow table").find(".arrow-up").remove(),$("#querywindow table").find(".arrow-down").remove(),
$("#querywindow table").find(".sorticon").remove(),$("#querywindow table .newsortcontrol").append('<div class="sorticon"></div>'),$(this).find(".sorticon").remove(),$(this).append('<div class="arrow-down"></div>')):0<$(this).find(".arrow-down").length?(b=!0,$(this).find(".arrow-down").remove(),$(this).append('<div class="arrow-up"></div>')):($(this).find(".arrow-up").remove(),$(this).append('<div class="arrow-down"></div>'));var c=$("#querywindow table"),e=c.find("tr").get();e.splice(0,1);e.sort(function(c,
e){var g=$(c).children("td:nth-child("+(a+1)+")").text(),h=$(e).children("td:nth-child("+(a+1)+")").text();return b?h.localeCompare(g):g.localeCompare(h)});$.each(e,function(a,b){c.children("tbody").append(b)})});b=$("#querywindow table").find("tr").get();b.splice(0,1);b.sort(function(a,b){var c=$(a).children("td:nth-child(1)").text(),e=$(b).children("td:nth-child(1)").text();return c.localeCompare(e)});$("#querywindow").dialog("open")}
function upload(){var b=new FileReader,c=document.getElementById("file").files[0];c&&(b.readAsText(c),b.onload=fileLoaded);return!1}
function confirmOverwrite(b,c){confirm(b+"\r\n\u8acb\u554f\u662f\u5426\u78ba\u5b9a\u8981\u8986\u84cb?")?$.ajax({url:"../../projects/uploadbatch",type:"POST",data:{data:c},async:!1,success:function(a){"success"==a.status?(alert("\u5c08\u6848\u532f\u5165\u6210\u529f"),location.reload(!0)):alert(a.errorMessage)},error:function(a,b,c){a=a.responseText;console.log(a);alert(a);alert(c)}}):alert("\u53d6\u6d88\u532f\u5165\u5c08\u6848")}
function fileLoaded(b){var c=b.target.result,c=c.replace(/(\r\n|\n|\r|\t)/gm,"");$.ajax({url:"../../projects/checkuploadbatch",type:"POST",data:{data:c},async:!1,success:function(a){"success"==a.status?(alert("\u5c08\u6848\u532f\u5165\u6210\u529f"),location.reload(!0)):"confirm"==a.status?confirmOverwrite(a.confirmMessage,c):alert(a.errorMessage)},error:function(a,b,c){a=a.responseText;console.log(a);alert(a);alert(c)}})}
function findPlatformFromURL(b){if(0<=b.indexOf("code.google.com"))return"googlecode";if(0<=b.indexOf("github.com"))return"github";if(0<=b.indexOf("www.openfoundry.org"))return"openfoundry";if(0<=b.indexOf("sourceforge.net"))return"sourceforge"}function getprojectfromrowid(b,c){var a=$(b).attr("id"),a=parseInt(a.replace("projectrow",""));return c[a]}function sortwithid(b,c,a){b=getprojectfromrowid(b,a);c=getprojectfromrowid(c,a);return b.project_id.localeCompare(c.project_id)}
function sortwithplatform(b,c,a){b=getprojectfromrowid(b,a);c=getprojectfromrowid(c,a);return b.platform.localeCompare(c.platform)}function sortwithyear(b,c,a){b=getprojectfromrowid(b,a);c=getprojectfromrowid(c,a);return b.year>c.year?1:b.year<c.year?-1:0}function sortwithprojectname(b,c,a){b=getprojectfromrowid(b,a);c=getprojectfromrowid(c,a);return b.name.localeCompare(c.name)}
function sortwithprojecthost(b,c,a){b=getprojectfromrowid(b,a);c=getprojectfromrowid(c,a);return b.leader.localeCompare(c.leader)}function sortwithclass(b,c,a){b=getprojectfromrowid(b,a);c=getprojectfromrowid(c,a);return b.type.localeCompare(c.type)}function sortwithfunction(b,c,a){var d=$("#projecttable"),f=d.find("tr").get();f.splice(0,1);f.sort(function(a,f){return b(a,f,c)});a&&f.reverse();$.each(f,function(a,b){d.children("tbody").append(b)})}
function sortprojects(b,c){var a=$(b).attr("value"),d,f;$(".sortcontrol").each(function(){var a=$(this).find(".arrow-up").length,b=$(this).find(".arrow-down").length;0<a&&(d=$(this).attr("value"),f=!1);0<b&&(d=$(this).attr("value"),f=!0)});$(".sortcontrol").find(".arrow-up").remove();$(".sortcontrol").find(".arrow-down").remove();var g=!0,e=!1;d==a&&(g=!f,e=!0);"year"==a?sortwithfunction(sortwithyear,c,!g):"id"==a?sortwithfunction(sortwithid,c,!g):"class"==a?sortwithfunction(sortwithclass,c,!g):"projectname"==
a?sortwithfunction(sortwithprojectname,c,!g):"platform"==a?sortwithfunction(sortwithplatform,c,!g):"projecthost"==a&&sortwithfunction(sortwithprojecthost,c,!g);g?b.append('<div class="arrow-down"></div>'):b.append('<div class="arrow-up"></div>');e||(b.find(".sorticon").remove(),$('.sortcontrol[value="'+d+'"]').append('<div class="sorticon"></div>'))}function compareNumbers(b,c){return b-c}
function hideunfittingprojects(b){var c={},a=0,d=0,f=[];$("#filteryearwindow input:checked").each(function(){f.push($(this).val())});for(a=0;a<b.length;a++)c[a]=!0;for(a=0;a<b.length;a++){for(var g=!1,d=0;d<f.length;d++)if(f[d]==b[a].year){g=!0;break}g||delete c[a]}f=[];$("#filterclasswindow input:checked").each(function(){f.push($(this).val())});for(var e in c){g=!1;for(a=0;a<b.length;a++)if(f[a]==b[e].type){g=!0;break}g||delete c[e]}f=[];$("#filterplatformwindow input:checked").each(function(){f.push($(this).val())});
for(e in c){g=!1;for(a=0;a<b.length;a++)if(f[a]==b[e].platform.replace(" ","_")){g=!0;break}g||delete c[e]}a=$("#idtb").val();if(0<a.length)for(e in c)0>b[e].project_id.indexOf(a)&&delete c[e];a=$("#projectnametb").val();if(0<a.length)for(e in c)0>b[e].name.indexOf(a)&&delete c[e];for(a=0;a<b.length;a++)a in c?$("#projectrow"+a).show():$("#projectrow"+a).hide()}
function clearmodifywindow(){$("#modprojyear").val("");$("#modprojclass").val("");$("#modprojid").val("");$("#modprojname").val("");$("#modprojplatform").val("")}
function renderprojecttable(b){0<$("#projwin").length&&$("#projwin").remove();var c;c="<table id=\"projecttable\" class=\"fancytable\"><tr><th class='sortcontrol' value = 'year'><span>\u5e74\u5ea6<div class='sorticon'></div></span></th><th class='sortcontrol' value = 'class'>\u985e\u5225<div class='sorticon'></div></th><th class='sortcontrol' value = 'id'>\u4ee3\u78bc<div class='arrow-down'></div></th><th class='sortcontrol' value = 'projectname'>\u5c08\u6848<div class='sorticon'></div></th><th class='sortcontrol' value = 'projecthost'>\u4e3b\u6301\u4eba<div class='sorticon'></div></th><th class='sortcontrol' value = 'platform'>\u5e73\u53f0<div class='sorticon'></div></th><th>\u522a\u9664</th><th>\u4fee\u6539</th><th>\u67e5\u8a62</th></tr>";var a;
for(a=0;a<b.length;a++)c+='<tr class="alt" id="projectrow'+a+'"><td>'+b[a].year+"</td><td>"+b[a].type+"</td><td>"+b[a].project_id+"</td><td>"+b[a].name+"</td><td>"+b[a].leader+'</td><td><a href="'+b[a].url+'">'+b[a].platform+'</a></td><td><button id="delete'+a+'">\u522a\u9664</button></td><td><button id="modify'+a+'">\u4fee\u6539</button></td><td><button id="query'+a+'">\u67e5\u8a62</button></td></tr>';c+="</table>";$("#deleteprojectwindow").append(c);for(a=0;a<b.length;a++)$("#modify"+a).click({value:a},
function(a){$("#modprojectwindow").dialog("open");selectedmodifyidx=a.data.value;$("#modprojyear").val(b[a.data.value].year);$("#modprojclass").val(b[a.data.value].type);$("#modprojid").val(b[a.data.value].project_id);$("#modprojname").val(b[a.data.value].name);$("#modprojleader").val(b[a.data.value].leader);$("#modprojplatform").val(b[a.data.value].url)}),$("#delete"+a).click({value:a},function(a){confirm("\u78ba\u5b9a\u8981\u522a\u9664"+b[a.data.value].project_id+"\u5c08\u6848?")&&$.ajax({url:"http://60.245.28.90/codeigniter/index.php/projects/deleteproject",
type:"POST",data:{project_id:b[a.data.value].project_id},async:!1,success:function(a){"success"==a.status?(alert("\u5c08\u6848\u522a\u9664\u6210\u529f"),location.reload(!0)):alert(a.errorMessage)},error:function(a,b,c){a=a.responseText;console.log(a);alert(a);alert(c)}})}),$("#query"+a).click({value:a},function(a){$.ajax({url:"http://60.245.28.90/codeigniter/index.php/projects/getprojectmodificationhistory",type:"POST",data:{project_id:b[a.data.value].project_id},async:!1,success:function(a){"success"==
a.status?renderHistory(a.history):alert(a.errorMessage)},error:function(a,b,c){a=a.responseText;console.log(a);alert(a);alert(c)}})})}var selectedmodifyidx=-1;
$(document).ready(function(){$.ajax({url:"../../projects/getgenericdata",type:"GET",async:!1,success:function(a){projects=a},error:function(a,b,c){alert(a.responseText);alert(c)}});renderprojecttable(projects);for(var b={},c=[],a=0,a=0;a<projects.length;a++)b[projects[a].year]=!0;for(var d in b)b.hasOwnProperty(d)&&c.push(d);c.sort(compareNumbers);b="";for(a=0;a<c.length;a++)b+='<input class="filtercheck" type="checkbox" value='+c[a]+" checked>"+c[a]+"\u5e74\u5ea6</input>";$("#filteryearwindow").append(b);
b={};c=[];for(a=0;a<projects.length;a++)b[projects[a].type]=!0;for(d in b)b.hasOwnProperty(d)&&c.push(d);b="";for(a=0;a<c.length;a++)b+='<input type="checkbox" class="filtercheck" value='+c[a]+" checked>"+c[a]+"</input>";$("#filterclasswindow").append(b);b={};c=[];for(a=0;a<projects.length;a++)b[projects[a].platform]=!0;for(d in b)b.hasOwnProperty(d)&&c.push(d);d="";for(a=0;a<c.length;a++)d+='<input type="checkbox" class="filtercheck" value='+c[a].replace(" ","_")+" checked>"+c[a]+"</input>";$("#filterplatformwindow").append(d);
$(".filtercheck").change(function(){hideunfittingprojects(projects)});$("#idtb").on("change keyup paste",function(){hideunfittingprojects(projects)});$("#projectnametb").on("change keyup paste",function(){hideunfittingprojects(projects)});$("#filteryearwindow").dialog({title:"\u904e\u6ffe\u5e74\u5ea6",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0,position:{my:"top",at:"bottom",of:$("#filteryearbutton")},buttons:[{text:"\u5168\u9078",click:function(){$(this).find(".filtercheck").prop("checked",
!0);hideunfittingprojects(projects)}},{text:"\u5168\u4e0d\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!1);hideunfittingprojects(projects)}},{text:"\u78ba\u5b9a",click:function(){$(this).dialog("close")}}]});$("#filteryearbutton").click(function(){$("#filteryearwindow").dialog("open")});$("#filterclasswindow").dialog({title:"\u904e\u6ffe\u985e\u5225",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0,position:{my:"top",at:"bottom",of:$("#filterclassbutton")},buttons:[{text:"\u5168\u9078",
click:function(){$(this).find(".filtercheck").prop("checked",!0);hideunfittingprojects(projects)}},{text:"\u5168\u4e0d\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!1);hideunfittingprojects(projects)}},{text:"\u78ba\u5b9a",click:function(){$(this).dialog("close")}}]});$("#filterclassbutton").click(function(){$("#filterclasswindow").dialog("open")});$("#filterplatformwindow").dialog({title:"\u904e\u6ffe\u5e73\u53f0",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0,
position:{my:"top",at:"bottom",of:$("#filterplatformbutton")},buttons:[{text:"\u5168\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!0);hideunfittingprojects(projects)}},{text:"\u5168\u4e0d\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!1);hideunfittingprojects(projects)}},{text:"\u78ba\u5b9a",click:function(){$(this).dialog("close")}}]});$("#filterplatformbutton").click(function(){$("#filterplatformwindow").dialog("open")});sortwithfunction(sortwithid,projects,
!1);$(".sortcontrol").click(function(){sortprojects($(this),projects)});$("#newprojectwindow").dialog({title:"\u65b0\u589e\u5c08\u6848",height:"auto",width:"auto",autoOpen:!1});$("#modprojectwindow").dialog({title:"\u4fee\u6539\u5c08\u6848",height:"auto",width:"auto",autoOpen:!1});$("#newprojbutton").click(function(){$("#newprojectwindow").dialog("open");$("#newprojectwindow").find("input").val("")});$("#newprojok").click(function(){$.ajax({url:"../../projects/setnewproject",type:"POST",data:{year:$("#newprojyear").val(),
type:$("#newprojclass").val(),project_id:$("#newprojid").val(),name:$("#newprojname").val(),platform:findPlatformFromURL($("#newprojplatform").val()),url:$("#newprojplatform").val(),leader:$("#newprojleader").val()},async:!1,success:function(a){"success"==a.status?(alert("\u5c08\u6848\u8cc7\u6599\u6210\u529f\u532f\u5165"),window.location.reload(!0)):alert(a.errorMessage)},error:function(a,b,c){a=a.responseText;console.log(a);alert(a);alert(c)}});$("#newprojectwindow").dialog("close")});$("#newprojcancel").click(function(){$("#newprojectwindow").dialog("close")});
$("#modsubmit").click(function(){$.ajax({url:"../../projects/modifyproject",type:"POST",data:{year:$("#modprojyear").val(),type:$("#modprojclass").val(),project_id:$("#modprojid").val(),name:$("#modprojname").val(),url:$("#modprojplatform").val(),leader:$("#modprojleader").val()},async:!1,success:function(a){"success"==a.status?(alert("\u5c08\u6848\u4fee\u6539\u6210\u529f"),window.location.reload(!0)):alert(a.errorMessage)},error:function(a,b,c){a=a.responseText;console.log(a);alert(a);alert(c)}})});
$("#modcancel").click(function(){clearmodifywindow();selectedmodifyidx=-1;$("#modprojectwindow").dialog("close")});$("#confirmwindow").dialog({title:"\u5c08\u6848\u4fee\u6539\u78ba\u8a8d",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0,buttons:[{text:"\u78ba\u8a8d",click:function(){$(this).find(".filtercheck").prop("checked",!0);hideunfittingprojects(projects)}},{text:"\u53d6\u6d88",click:function(){$(this).find(".filtercheck").prop("checked",!1);hideunfittingprojects(projects)}}]})});
$("#querywindow").dialog({title:"\u4fee\u6539\u7d00\u9304\u67e5\u8a62",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0});
