function exportToExcel(){var b={},a={},c=[];a.year="";$("#filteryearwindow input:checked").each(function(){a.year+=","+$(this).val()});a.year=a.year.substring(1);a.type=[];$("#filterclasswindow input:checked").each(function(){a.type+=","+$(this).val()});a.type=a.type.substring(1);a.codeName=$("#idtb").val();a.projectName=$("#projectnametb").val();a.platform=[];$("#filterplatformwindow input:checked").each(function(){a.platform+=","+$(this).val()});a.platform=a.platform.substring(1);$("#projecttable tr").each(function(){var a=
[];$(this).find("th:visible").each(function(){a.push($(this).text().replace("\r\n","").replace("\n","").replace("\r",""))});$(this).find("td:visible").each(function(){a.push($(this).text().replace("\r\n","").replace("\n","").replace("\r",""))});0<a.length&&c.push(a)});b.filter=a;b.data=c;var d="";$.ajax({url:"../../export/setdata",type:"POST",data:{content:b},async:!1,success:function(a){d=a.filename},error:function(a,b,c){alert(a.responseText);alert(c)}});window.open("../../export/getfile/"+d)}
function getprojectfromrowid(b,a){var c=$(b).attr("id"),c=parseInt(c.replace("projectrow",""));return a[c]}function sortwithid(b,a,c){b=getprojectfromrowid(b,c);a=getprojectfromrowid(a,c);return b.project_id.localeCompare(a.project_id)}function sortwithplatform(b,a,c){b=getprojectfromrowid(b,c);a=getprojectfromrowid(a,c);return b.platform.localeCompare(a.platform)}function sortwithyear(b,a,c){b=getprojectfromrowid(b,c);a=getprojectfromrowid(a,c);return b.year>a.year?1:b.year<a.year?-1:0}
function sortwithprojectname(b,a,c){b=getprojectfromrowid(b,c);a=getprojectfromrowid(a,c);return b.name.localeCompare(a.name)}function sortwithprojecthost(b,a,c){b=getprojectfromrowid(b,c);a=getprojectfromrowid(a,c);return b.leader.localeCompare(a.leader)}function sortwithclass(b,a,c){b=getprojectfromrowid(b,c);a=getprojectfromrowid(a,c);return b.type.localeCompare(a.type)}
function sortwithfunction(b,a,c){var d=$("#projecttable"),e=d.find("tr").get();e.splice(0,1);e.sort(function(c,d){return b(c,d,a)});c&&e.reverse();$.each(e,function(a,b){d.children("tbody").append(b)})}
function sortprojects(b,a){var c=$(b).attr("value"),d,e;$(".sortcontrol").each(function(){var a=$(this).find(".arrow-up").length,b=$(this).find(".arrow-down").length;0<a&&(d=$(this).attr("value"),e=!1);0<b&&(d=$(this).attr("value"),e=!0)});$(".sortcontrol").find(".arrow-up").remove();$(".sortcontrol").find(".arrow-down").remove();var f=!0,g=!1;d==c&&(f=!e,g=!0);"year"==c?sortwithfunction(sortwithyear,a,!f):"id"==c?sortwithfunction(sortwithid,a,!f):"class"==c?sortwithfunction(sortwithclass,a,!f):"projectname"==
c?sortwithfunction(sortwithprojectname,a,!f):"platform"==c?sortwithfunction(sortwithplatform,a,!f):"projecthost"==c&&sortwithfunction(sortwithprojecthost,a,!f);f?b.append('<div class="arrow-down"></div>'):b.append('<div class="arrow-up"></div>');g||(b.find(".sorticon").remove(),$('.sortcontrol[value="'+d+'"]').append('<div class="sorticon"></div>'))}
function plottrendgraph(b,a,c,d,e,f){if(void 0==d)alert("\u6b64\u5c08\u6848\u5c1a\u7121\u8cc7\u6599");else if(0==d.length)alert("\u6b64\u5c08\u6848\u5c1a\u7121\u8cc7\u6599");else{for(var g=0;g<d.length;++g)d[g][1]=parseInt(d[g][1]);d.sort(function(a,b){return b[0].localeCompare(a[0])});"all"!=e&&d.length>parseInt(e)&&(d=d.splice(0,parseInt(e)));e=[];for(g=0;g<d.length;++g){var l=d[g][1],h=-1;e.push(d[g]);for(var k=g+1;k<d.length;++k)if(d[k][1]==l)h=k;else break;0<=h&&(e.push(d[h]),g=h)}$.jqplot(b,
[e],{title:f,axes:{xaxis:{renderer:$.jqplot.DateAxisRenderer,tickOptions:{formatString:"%b %d"},label:a},yaxis:{tickRenderer:$.jqplot.AxisTickRenderer,tickOptions:{show:!0},label:c}},series:[{pointLabels:{show:!0,edgeTolerance:-50}}],animate:!0,animateReplot:!0})}}var projectStatus={};
function loadStatusViewer(b){$.ajax({url:"../../projects/getstatusgraphdata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){projectStatus=a},error:function(a,b,d){alert(a.responseText);alert(d)}});$("#statusviewer .statusviewtype").off("change");$("#statusviewer .statusviewtype").change(function(){plotStatusViewer()});$("#statusviewer .showplot").off("click");$("#statusviewer .showplot").click(function(){plotStatusViewer()});$("#statusviewer").dialog("option","title",b.project_id+
" \u72c0\u614b\u6b77\u53f2\u8cc7\u6599");$("#statusviewer").dialog("open");plotStatusViewer()}function extractData(b,a){var c=[],d;for(d in projectStatus){var e=[d,parseInt(projectStatus[d][b][a])];c.push(e)}return c}
function plotStatusViewer(){if(0==projectStatus.length)alert("\u6b64\u5c08\u6848\u5c1a\u7121\u8cc7\u6599");else{var b=$("#statusviewer .statusviewtype :selected").val(),a=fillZeroDates(extractData(b,"all_success")),c=fillZeroDates(extractData(b,"success_update")),d=fillZeroDates(extractData(b,"no_change")),e=fillZeroDates(extractData(b,"all_fail")),f=fillZeroDates(extractData(b,"cannot_get_data")),g=fillZeroDates(extractData(b,"can_not_resolve")),l=fillZeroDates(extractData(b,"no_proxy")),b=fillZeroDates(extractData(b,
"proxy_error")),h=Math.floor((Date.parse(a[a.length-1][0])-Date.parse(a[0][0]))/864E5),k=parseInt($("#statusgraph").css("width")),m=1;0<h&&(m=Math.ceil(h/(k/50)));$("#statusgraph").empty();a=$.jqplot("statusgraph",[a,c,d,e,f,g,l,b],{title:"\u72c0\u614b\u5716\u8868",axes:{xaxis:{renderer:$.jqplot.DateAxisRenderer,tickRenderer:$.jqplot.CanvasAxisTickRenderer,tickOptions:{formatString:"%b %d"},tickInterval:m+" day"},yaxis:{min:0}},highlighter:{show:!0},animate:!0,animateReplot:!0,legend:{show:!0,location:"e",
placement:"inside",labels:"\u6210\u529f \u8cc7\u6599\u6539\u8b8a\u4e14\u532f\u5165\u6210\u529f \u8cc7\u6599\u7121\u6539\u8b8a \u5931\u6557 \u7121\u6cd5\u53d6\u5f97\u8cc7\u6599\u9801\u9762 \u89e3\u6790\u5931\u6557 \u7121Proxy\u53ef\u7528 Proxy\u932f\u8aa4".split(" ")}});a.series[0].show=$('#statusviewer .showplot[value="all_success"').prop("checked");a.series[1].show=$('#statusviewer .showplot[value="success_update"').prop("checked");a.series[2].show=$('#statusviewer .showplot[value="no_change"').prop("checked");
a.series[3].show=$('#statusviewer .showplot[value="fail"').prop("checked");a.series[4].show=$('#statusviewer .showplot[value="cannot_get_data"').prop("checked");a.series[5].show=$('#statusviewer .showplot[value="can_not_resolve"').prop("checked");a.series[6].show=$('#statusviewer .showplot[value="no_proxy"').prop("checked");a.series[7].show=$('#statusviewer .showplot[value="proxy_error"').prop("checked");a.replot()}}var crawlstatus={};
function loadcrawlerviewer(b){$.ajax({url:"../../projects/getproxygraphdata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){crawlstatus=a},error:function(a,b,c){alert(a.responseText);alert(c)}});var a=[],c;for(c in crawlstatus)a=a.concat(crawlstatus[c]);a.sort(function(a,b){var c=new Date(a.day),d=new Date(b.day);return c.getTime()<d.getTime()?-1:c.getTime()>d.getTime()?1:0});for(var d=[],e=0;e<a.length;++e)d.hasOwnProperty(a[e].day)?(d[a[e].day].all_success+=a[e].all_success,
d[a[e].day].success_update+=a[e].success_update,d[a[e].day].no_change+=a[e].no_change,d[a[e].day].fail+=a[e].fail):(d[a[e].day]={},d[a[e].day].all_success=a[e].all_success,d[a[e].day].success_update=a[e].success_update,d[a[e].day].no_change=a[e].no_change,d[a[e].day].fail=a[e].fail),d[a[e].day].day=a[e].day;a=[];for(c in d)a=a.concat(d[c]);crawlstatus.all=a;$("#crawlerviewer .crawlerselect").empty();for(c in crawlstatus)"all"==c?$("#crawlerviewer .crawlerselect").append($('<option value="all">\u5168\u90e8</option>')):
$("#crawlerviewer .crawlerselect").append($("<option></option>").attr("value",c).text(c));$("#crawlerviewer .crawlerselect").off("change");$("#crawlerviewer .crawlerselect").change(function(){plotcrawlerviewer()});$("#crawlerviewer .showplot").off("click");$("#crawlerviewer .showplot").click(function(){plotcrawlerviewer()});$("#crawlerviewer").dialog("option","title",b.project_id+" crawler\u6b77\u53f2\u8cc7\u6599");$("#crawlerviewer").dialog("open");plotcrawlerviewer()}
function extractWithPropertyName(b,a){for(var c=[],d=0;d<b.length;++d)c.push([b[d].day,b[d][a]]);return c}function fillZeroDates(b){if(void 0===b||0==b.length)return b;var a=new Date(b[0][0]),c=[];c.push(b[0]);for(var d=1;d<b.length;++d){a=new Date(b[d-1][0]);a.setDate(a.getDate()+1);for(var e=new Date(b[d][0]);a<e;a.setDate(a.getDate()+1)){var f=new Date(a);f.setHours(0,0,0,0);f=[f.getFullYear()+"-"+(f.getMonth()+1)+"-"+f.getDate(),0];c.push(f)}c.push(b[d])}return c}
function plotcrawlerviewer(){$("#crawlergraph").empty();if(0==crawlstatus.length)alert("\u6b64\u5c08\u6848\u5c1a\u7121\u8cc7\u6599");else{var b=$("#crawlerviewer .crawlerselect").val(),a=fillZeroDates(extractWithPropertyName(crawlstatus[b],"all_success")),c=fillZeroDates(extractWithPropertyName(crawlstatus[b],"success_update")),d=fillZeroDates(extractWithPropertyName(crawlstatus[b],"no_change")),b=fillZeroDates(extractWithPropertyName(crawlstatus[b],"fail")),e=Math.floor((Date.parse(a[a.length-1][0])-
Date.parse(a[0][0]))/864E5),f=parseInt($("#crawlergraph").css("width")),g=1;0<e&&(g=Math.ceil(e/(f/50)));a=$.jqplot("crawlergraph",[a,c,d,b],{title:"Proxy status",axes:{xaxis:{renderer:$.jqplot.DateAxisRenderer,tickOptions:{formatString:"%b %d"},tickInterval:g+" day"},yaxis:{min:0}},highlighter:{show:!0},legend:{show:!0,location:"e",placement:"inside",labels:["\u6210\u529f","\u8cc7\u6599\u6539\u8b8a\u4e14\u532f\u5165\u6210\u529f","\u8cc7\u6599\u7121\u6539\u8b8a","\u5931\u6557"]},animate:!0,animateReplot:!0});
a.series[0].show=$('#crawlerviewer .showplot[value="all_success"').prop("checked");a.series[1].show=$('#crawlerviewer .showplot[value="success_update"').prop("checked");a.series[2].show=$('#crawlerviewer .showplot[value="no_change"').prop("checked");a.series[3].show=$('#crawlerviewer .showplot[value="fail"').prop("checked");a.replot()}}var downloaddata=[],downloadsinglefiledata=[],organizeddownloadsinglefiledata={};
function loaddownloadviewer(b){$.ajax({url:"../../projects/getdownloadgraphdata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){downloaddata=a},error:function(a,b,c){alert(a.responseText)}});$.ajax({url:"../../projects/getdownloadsinglefilegraphdata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){downloadsinglefiledata=a},error:function(){alert("\u7121\u6cd5\u53d6\u5f97\u5c08\u6848\u57fa\u672c\u8cc7\u6599\uff0c\u8acb\u91cd\u65b0\u6574\u7406\u6b64\u9801\u9762")}});
for(var a={},c=0;c<downloadsinglefiledata.length;++c)a[downloadsinglefiledata[c].name]=!0;for(var d in a){for(var e=[],c=0;c<downloadsinglefiledata.length;++c)downloadsinglefiledata[c].name==d&&e.push(downloadsinglefiledata[c]);organizeddownloadsinglefiledata[d]=e}$("#downloadviewer").find(".threadnamelist").empty();var c="",f;for(f in a)c+='<option value="'+f+'">'+f+"</option>";$("#downloadviewer").find(".threadnamelist").append(c);$("#downloadviewer").dialog("option","title",b.project_id+"download\u6b77\u53f2\u8cc7\u6599");
$("#downloadviewer").dialog("open");plotdownloadviewer();$("#downloadviewer").find(".displaytype").off("change");$("#downloadviewer").find(".displaytype").change(function(){0>$("#downloadviewer").find(".displaytype :selected").val().indexOf("total")?$("#downloadviewer").find(".singlethreadpanel").show():$("#downloadviewer").find(".singlethreadpanel").hide();plotdownloadviewer()});$("#downloadviewer").find(".threadnamelist").off("change");$("#downloadviewer").find(".threadnamelist").change(function(){plotdownloadviewer()});
$("#downloadviewer").find(".numdatas").off("change");$("#downloadviewer").find(".numdatas").change(function(){plotdownloadviewer()})}
function plotdownloadviewer(){$("#downloadgraph").empty();var b=$("#downloadviewer").find(".displaytype :selected").val();if("totalfiles"==b){for(var b=[],a=0;a<downloaddata.length;++a)b.push([downloaddata[a].timestamp,downloaddata[a].totalfiles]);plottrendgraph("downloadgraph","\u65e5\u671f","\u7e3d\u6a94\u6848\u6578",b,$("#downloadviewer .numdatas :selected").val(),"Download \u5716\u8868")}else if("totaldownloads"==b){b=[];for(a=0;a<downloaddata.length;++a)b.push([downloaddata[a].timestamp,downloaddata[a].totaldownloads]);
plottrendgraph("downloadgraph","\u65e5\u671f","\u7e3d\u4e0b\u8f09\u6b21\u6578",b,$("#downloadviewer .numdatas :selected").val(),"Download \u5716\u8868")}else if("singledownloads"==b){for(var c=$("#downloadviewer").find(".threadnamelist :selected").val(),b=[],a=0;a<organizeddownloadsinglefiledata[c].length;++a)b.push([organizeddownloadsinglefiledata[c][a].timestamp,organizeddownloadsinglefiledata[c][a].count]);plottrendgraph("downloadgraph","\u65e5\u671f","\u55ae\u4e00\u6a94\u6848\u4e0b\u8f09\u6b21\u6578",
b,$("#downloadviewer .numdatas :selected").val(),"Download \u5716\u8868")}}var issuetrackerdata=[];
function loadissuetrackerviewer(b){$.ajax({url:"../../projects/getissuetrackergraphdata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){issuetrackerdata=a},error:function(){alert("\u7121\u6cd5\u53d6\u5f97\u5c08\u6848\u57fa\u672c\u8cc7\u6599\uff0c\u8acb\u91cd\u65b0\u6574\u7406\u6b64\u9801\u9762")}});$("#issuetrackerviewer").dialog("option","title",b.project_id+" issue tracker\u6b77\u53f2\u8cc7\u6599");$("#issuetrackerviewer").dialog("open");plotissuetrackerviewer();$("#issuetrackerviewer").find(".displaytype").off("change");
$("#issuetrackerviewer").find(".displaytype").change(function(){plotissuetrackerviewer()});$("#issuetrackerviewer").find(".numdatas").off("change");$("#issuetrackerviewer").find(".numdatas").change(function(){plotissuetrackerviewer()})}
function plotissuetrackerviewer(){$("#issuetrackergraph").empty();var b=$("#issuetrackerviewer").find(".displaytype :selected").val();if("totalthreads"==b){for(var b=[],a=0;a<issuetrackerdata.length;++a)b.push([issuetrackerdata[a].timestamp,issuetrackerdata[a].topic]);plottrendgraph("issuetrackergraph","\u65e5\u671f","\u4e3b\u984c\u7e3d\u6578",b,$("#issuetrackerviewer .numdatas :selected").val(),"Issue Tracker \u5716\u8868")}else if("totalreplies"==b){b=[];for(a=0;a<issuetrackerdata.length;++a)b.push([issuetrackerdata[a].timestamp,
issuetrackerdata[a].article]);plottrendgraph("issuetrackergraph","\u65e5\u671f","\u56de\u61c9\u7e3d\u6578",b,$("#issuetrackerviewer .numdatas :selected").val(),"Issue Tracker \u5716\u8868")}else if("totalaccounts"==b){b=[];for(a=0;a<issuetrackerdata.length;++a)b.push([issuetrackerdata[a].timestamp,issuetrackerdata[a].account]);plottrendgraph("issuetrackergraph","\u65e5\u671f","\u4e0d\u540c\u5e33\u865f\u7e3d\u6578",b,$("#issuetrackerviewer .numdatas :selected").val(),"Issue Tracker \u5716\u8868")}else if("openthreads"==
b){b=[];for(a=0;a<issuetrackerdata.length;++a)b.push([issuetrackerdata[a].timestamp,issuetrackerdata[a].open]);plottrendgraph("issuetrackergraph","\u65e5\u671f","open\u4e3b\u984c\u6578",b,$("#issuetrackerviewer .numdatas :selected").val(),"Issue Tracker \u5716\u8868")}else if("closethreads"==b){b=[];for(a=0;a<issuetrackerdata.length;++a)b.push([issuetrackerdata[a].timestamp,issuetrackerdata[a].close]);plottrendgraph("issuetrackergraph","\u65e5\u671f","close\u4e3b\u984c\u6578",b,$("#issuetrackerviewer .numdatas :selected").val(),
"Issue Tracker \u5716\u8868")}}var vcsdata=[],vcscommiterdata=[],organizedvcscommiterdata={};
function loadvcsviewer(b){$.ajax({url:"../../projects/getvcsgraphdata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){vcsdata=a},error:function(){alert("\u7121\u6cd5\u53d6\u5f97\u5c08\u6848\u57fa\u672c\u8cc7\u6599\uff0c\u8acb\u91cd\u65b0\u6574\u7406\u6b64\u9801\u9762")}});$.ajax({url:"../../projects/getvcscommitergraphdata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){vcscommiterdata=a},error:function(){alert("\u7121\u6cd5\u53d6\u5f97\u5c08\u6848\u57fa\u672c\u8cc7\u6599\uff0c\u8acb\u91cd\u65b0\u6574\u7406\u6b64\u9801\u9762")}});
for(var a={},c=0;c<vcscommiterdata.length;++c)a[vcscommiterdata[c].timestamp]=!0;for(var d in a){for(var e=[],c=0;c<vcscommiterdata.length;++c)vcscommiterdata[c].timestamp==d&&e.push(vcscommiterdata[c]);organizedvcscommiterdata[d]=e}$("#vcsviewer").find(".datelist").empty();var c="",f;for(f in a)c+='<option value="'+f+'">'+f+"</option>";$("#vcsviewer").find(".datelist").append(c);$("#vcsviewer").dialog("option","title",b.project_id+" vcs\u6b77\u53f2\u8cc7\u6599");$("#vcsviewer").dialog("open");plotvcsviewer();
$("#vcsviewer").find(".displaytype").off("change");$("#vcsviewer").find(".displaytype").change(function(){0>$("#vcsviewer").find(".displaytype :selected").val().indexOf("total")?$("#vcsviewer").find(".contributionpanel").show():$("#vcsviewer").find(".contributionpanel").hide();plotvcsviewer()});$("#vcsviewer").find(".datelist").off("change");$("#vcsviewer").find(".datelist").change(function(){plotvcsviewer()});$("#vcsviewer").find(".numdatas").off("change");$("#vcsviewer").find(".numdatas").change(function(){plotvcsviewer()})}
function plotvcsviewer(){$("#vcsgraph").empty();var b=$("#vcsviewer").find(".displaytype :selected").val();"usercontribution"!=b&&$("#vcsgraph").css("height","450px");if("totalcommits"==b){for(var a=[],b=0;b<vcsdata.length;++b)a.push([vcsdata[b].timestamp,vcsdata[b].commit]);plottrendgraph("vcsgraph","\u65e5\u671f","\u7e3dcommit\u6578",a,$("#vcsviewer .numdatas :selected").val(),"VCS \u5716\u8868")}else if("totallines"==b){a=[];for(b=0;b<vcsdata.length;++b)a.push([vcsdata[b].timestamp,vcsdata[b].line]);
plottrendgraph("vcsgraph","\u65e5\u671f","\u7e3d\u884c\u6578",a,$("#vcsviewer .numdatas :selected").val(),"VCS \u5716\u8868")}else if("totalfiles"==b){a=[];for(b=0;b<vcsdata.length;++b)a.push([vcsdata[b].timestamp,vcsdata[b].file]);plottrendgraph("vcsgraph","\u65e5\u671f","\u7e3d\u6a94\u6848\u6578",a,$("#vcsviewer .numdatas :selected").val(),"VCS \u5716\u8868")}else if("totalfilesize"==b){a=[];for(b=0;b<vcsdata.length;++b)a.push([vcsdata[b].timestamp,vcsdata[b].size]);plottrendgraph("vcsgraph","\u65e5\u671f",
"\u7e3d\u6a94\u6848\u5927\u5c0f(KB)",a,$("#vcsviewer .numdatas :selected").val(),"VCS \u5716\u8868")}else if("totalusers"==b){a=[];for(b=0;b<vcsdata.length;++b)a.push([vcsdata[b].timestamp,vcsdata[b].user]);plottrendgraph("vcsgraph","\u65e5\u671f","\u7e3d\u8ca2\u737b\u8005\u6578",a,$("#vcsviewer .numdatas :selected").val(),"VCS \u5716\u8868")}else if("usercontribution"==b){var a=$("#vcsviewer").find(".datelist :selected").val(),c=[],d=[],e=[],b=organizedvcscommiterdata[a].length;$("#vcsgraph").css("height",
Math.max(450,70*b)+"px");for(b=0;b<organizedvcscommiterdata[a].length;++b)c.push([organizedvcscommiterdata[a][b]["new"],organizedvcscommiterdata[a][b].commiter]),d.push([organizedvcscommiterdata[a][b].modify,organizedvcscommiterdata[a][b].commiter]),e.push([organizedvcscommiterdata[a][b]["delete"],organizedvcscommiterdata[a][b].commiter]);$.jqplot("vcsgraph",[c,d,e],{seriesDefaults:{renderer:$.jqplot.BarRenderer,pointLabels:{show:!0,location:"e",edgeTolerance:-15},shadowAngle:135,rendererOptions:{barDirection:"horizontal"}},
series:[{label:"Add"},{label:"Modify"},{label:"Delete"}],axes:{yaxis:{renderer:$.jqplot.CategoryAxisRenderer}},legend:{show:!0,placement:"inside",rendererOptions:{numberRows:1},location:"ne",marginTop:"15px"}})}}var wikidata=[],wikisinglethreaddata=[],organizedwikisinglethreaddata={};
function loadwikiviewer(b){$.ajax({url:"../../projects/getwikigraphdata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){wikidata=a},error:function(){alert("\u7121\u6cd5\u53d6\u5f97\u5c08\u6848\u57fa\u672c\u8cc7\u6599\uff0c\u8acb\u91cd\u65b0\u6574\u7406\u6b64\u9801\u9762")}});$.ajax({url:"../../projects/getwikigraphsinglethreaddata",type:"POST",data:{project_id:b.project_id},async:!1,success:function(a){wikisinglethreaddata=a},error:function(){alert("\u7121\u6cd5\u53d6\u5f97\u5c08\u6848\u57fa\u672c\u8cc7\u6599\uff0c\u8acb\u91cd\u65b0\u6574\u7406\u6b64\u9801\u9762")}});
for(var a={},c=0;c<wikisinglethreaddata.length;++c)a[wikisinglethreaddata[c].title]=!0;for(var d in a){for(var e=[],c=0;c<wikisinglethreaddata.length;++c)wikisinglethreaddata[c].title==d&&e.push(wikisinglethreaddata[c]);organizedwikisinglethreaddata[d]=e}$("#wikiviewer").find(".threadnamelist").empty();var c="",f;for(f in a)c+='<option value="'+f+'">'+f+"</option>";$("#wikiviewer").find(".threadnamelist").append(c);$("#wikiviewer").dialog("option","title",b.project_id+" wiki\u6b77\u53f2\u8cc7\u6599");
$("#wikiviewer").dialog("open");plotwikiviewer();$("#wikiviewer").find(".displaytype").off("change");$("#wikiviewer").find(".displaytype").change(function(){0>$("#wikiviewer").find(".displaytype :selected").val().indexOf("total")?$("#wikiviewer").find(".singlethreadpanel").show():$("#wikiviewer").find(".singlethreadpanel").hide();plotwikiviewer()});$("#wikiviewer").find(".threadnamelist").off("change");$("#wikiviewer").find(".threadnamelist").change(function(){plotwikiviewer()});$("#wikiviewer").find(".numdatas").off("change");
$("#wikiviewer").find(".numdatas").change(function(){plotwikiviewer()})}
function plotwikiviewer(){$("#wikigraph").empty();var b=$("#wikiviewer").find(".displaytype :selected").val();if("totalthreads"==b){for(var b=[],a=0;a<wikidata.length;++a)b.push([wikidata[a].timestamp,wikidata[a].pages]);plottrendgraph("wikigraph","\u65e5\u671f","\u7e3d\u7bc7\u6578",b,$("#wikiviewer .numdatas :selected").val(),"Wiki \u5716\u8868")}else if("totalwords"==b){b=[];for(a=0;a<wikidata.length;++a)b.push([wikidata[a].timestamp,wikidata[a].word]);plottrendgraph("wikigraph","\u65e5\u671f",
"\u7e3d\u5b57\u6578",b,$("#wikiviewer .numdatas :selected").val(),"Wiki \u5716\u8868")}else if("totalupdates"==b){b=[];for(a=0;a<wikidata.length;++a)b.push([wikidata[a].timestamp,wikidata[a].update]);plottrendgraph("wikigraph","\u65e5\u671f","\u7e3d\u66f4\u65b0\u6578",b,$("#wikiviewer .numdatas :selected").val(),"Wiki \u5716\u8868")}else if("singlethreadwords"==b){for(var c=$("#wikiviewer").find(".threadnamelist :selected").val(),b=[],a=0;a<organizedwikisinglethreaddata[c].length;++a)b.push([organizedwikisinglethreaddata[c][a].timestamp,
organizedwikisinglethreaddata[c][a].word]);plottrendgraph("wikigraph","\u65e5\u671f","\u55ae\u4e00\u7bc7\u5b57\u6578",b,$("#wikiviewer .numdatas :selected").val(),"Wiki \u5716\u8868")}else if("singlethreadupdates"==b){c=$("#wikiviewer").find(".threadnamelist :selected").val();b=[];for(a=0;a<organizedwikisinglethreaddata[c].length;++a)b.push([organizedwikisinglethreaddata[c][a].timestamp,organizedwikisinglethreaddata[c][a].update]);plottrendgraph("wikigraph","\u65e5\u671f","\u55ae\u4e00\u7bc7\u66f4\u65b0\u6578",
b,$("#wikiviewer .numdatas :selected").val(),"Wiki \u5716\u8868")}}
function hideunfittingprojects(b){var a={},c=0,d=0,e=[];$("#filteryearwindow input:checked").each(function(){e.push($(this).val())});for(c=0;c<b.length;c++)a[c]=!0;for(c=0;c<b.length;c++){for(var f=!1,d=0;d<e.length;d++)if(e[d]==b[c].year){f=!0;break}f||delete a[c]}e=[];$("#filterclasswindow input:checked").each(function(){e.push($(this).val())});for(var g in a){f=!1;for(c=0;c<b.length;c++)if(e[c]==b[g].type){f=!0;break}f||delete a[g]}e=[];$("#filterplatformwindow input:checked").each(function(){e.push($(this).val())});
for(g in a){f=!1;for(c=0;c<b.length;c++)if(e[c]==b[g].platform.replace(" ","_")){f=!0;break}f||delete a[g]}c=$("#idtb").val();if(0<c.length)for(g in a)0>b[g].project_id.indexOf(c)&&delete a[g];c=$("#projectnametb").val();if(0<c.length)for(g in a)0>b[g].name.indexOf(c)&&delete a[g];for(c=0;c<b.length;c++)c in a?$("#projectrow"+c).show():$("#projectrow"+c).hide()}function compareNumbers(b,a){return b-a}
$(document).ready(function(){var b=[];$.ajax({url:"../../projects/getgenericdata",type:"GET",async:!1,success:function(a){b=a},error:function(){alert("\u7121\u6cd5\u53d6\u5f97\u5c08\u6848\u57fa\u672c\u8cc7\u6599\uff0c\u8acb\u91cd\u65b0\u6574\u7406\u6b64\u9801\u9762")}});$("#wikiviewer").dialog({autoOpen:!1,height:"auto",width:"auto"});$("#vcsviewer").dialog({autoOpen:!1,height:"auto",width:"auto"});$("#issuetrackerviewer").dialog({autoOpen:!1,height:"auto",width:"auto"});$("#downloadviewer").dialog({autoOpen:!1,
height:"auto",width:"auto"});$("#crawlerviewer").dialog({autoOpen:!1,height:"auto",width:"auto"});$("#statusviewer").dialog({autoOpen:!1,height:"auto",width:"auto"});for(var a={},c=[],d=0,d=0;d<b.length;d++)a[b[d].year]=!0;for(var e in a)a.hasOwnProperty(e)&&c.push(e);c.sort(compareNumbers);a="";for(d=0;d<c.length;d++)a+='<input class="filtercheck" type="checkbox" value='+c[d]+" checked>"+c[d]+"\u5e74\u5ea6</input>";$("#filteryearwindow").append(a);a={};c=[];for(d=0;d<b.length;d++)a[b[d].type]=!0;
for(e in a)a.hasOwnProperty(e)&&c.push(e);a="";for(d=0;d<c.length;d++)a+='<input type="checkbox" class="filtercheck" value="'+c[d]+'" checked>'+c[d]+"</input>";$("#filterclasswindow").append(a);a={};c=[];for(d=0;d<b.length;d++)a[b[d].platform]=!0;for(e in a)a.hasOwnProperty(e)&&c.push(e);e="";for(d=0;d<c.length;d++)e+='<input type="checkbox" class="filtercheck" value='+c[d].replace(" ","_")+" checked>"+c[d]+"</input>";$("#filterplatformwindow").append(e);e="";for(d=0;d<b.length;d++)e+='<tr class="alt" id="projectrow'+
d+'">',e+="<td>"+b[d].year+"</td><td>"+b[d].type+"</td><td>"+b[d].project_id+"</td><td>"+b[d].name+"</td><td>"+b[d].leader+'</td><td><a href="'+b[d].url+'">'+b[d].platform+"</a></td>",e+='<td><span class="wikiviewertext" projectidx='+d+">\u7e3d\u5171"+b[d].wiki_pages+"\u7bc7<br>\u7e3d\u5171"+b[d].wiki_word+"\u5b57<br>\u7e3d\u5171"+b[d].wiki_update+"\u6b21\u66f4\u65b0</span></td>",e+='<td><span class="issuetrackerviewertext" projectidx='+d+">\u7e3d\u5171"+b[d].issue_topic+"\u7b46\u4e3b\u984c<br>\u7e3d\u5171"+
b[d].issue_post+"\u7bc7\u6587\u7ae0<br>\u7e3d\u5171"+b[d].issue_user+"\u4e0d\u540c\u5e33\u865f\u53c3\u4e88<br>\u7248\u672c\u63a7\u5236\uff1a"+b[d].vcs_type+"</span></td>",e+='<td><span class="vcsviewertext" projectidx='+d+">\u7e3d\u5171"+b[d].vcs_commit+"\u6b21commit<br>\u7e3d\u5171"+b[d].vcs_line+"\u884c<br>\u7e3d\u5171"+b[d].vcs_file+"\u500b\u6a94\u6848<br>\u7e3d\u5171"+b[d].vcs_size+"<br>\u7e3d\u5171"+b[d].vcs_user+"\u4e0d\u540c\u5e33\u865f\u53c3\u4e88</span></td>",e+='<td><span class="downloadviewertext" projectidx='+
d+">\u7e3d\u5171"+b[d].dl_file+"\u500b\u6a94\u6848<br>\u7e3d\u5171"+b[d].dl_count+"\u6b21\u4e0b\u8f09</span></td>",e+="<td>",e="googlecode"==b[d].platform?e+("Starred by "+b[d].star+" users"):"github"==b[d].platform?e+("Star: "+b[d].star+" <br>Watched: "+b[d].watch+"<br>Fork: "+b[d].fork):"sourceforge"==b[d].platform?e+("5-Stars: "+b[d]["5-star"]+"<br>4-Stars: "+b[d]["4-star"]+"<br>3-Stars: "+b[d]["3-star"]+"<br>2-Stars: "+b[d]["2-star"]+"<br>1-Star: "+b[d]["1-star"]):e+"N/A",e+="</td>",e+="<td>"+
b[d].last_update+"</td>",e+='<td><span class="crawlertext" projectidx='+d+">"+b[d].proxy_ip+"</span></td>",e+='<td><span class="statustext" projectidx='+d+">"+b[d].status+"</span></td></tr>";$("#projecttable").append(e);$("#projecttable").find(".wikiviewertext").click(function(){loadwikiviewer(b[$(this).attr("projectidx")])});$("#projecttable").find(".vcsviewertext").click(function(){loadvcsviewer(b[$(this).attr("projectidx")])});$("#projecttable").find(".issuetrackerviewertext").click(function(){loadissuetrackerviewer(b[$(this).attr("projectidx")])});
$("#projecttable").find(".downloadviewertext").click(function(){loaddownloadviewer(b[$(this).attr("projectidx")])});$("#projecttable").find(".crawlertext").click(function(){loadcrawlerviewer(b[$(this).attr("projectidx")])});$("#projecttable").find(".statustext").click(function(){loadStatusViewer(b[$(this).attr("projectidx")])});$(".filtercheck").change(function(){hideunfittingprojects(b)});$("#idtb").on("change keyup paste",function(){hideunfittingprojects(b)});$("#projectnametb").on("change keyup paste",
function(){hideunfittingprojects(b)});$("#filteryearwindow").dialog({title:"\u904e\u6ffe\u5e74\u5ea6",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0,position:{my:"top",at:"bottom",of:$("#filteryearbutton")},buttons:[{text:"\u5168\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!0);hideunfittingprojects(b)}},{text:"\u5168\u4e0d\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!1);hideunfittingprojects(b)}},{text:"\u78ba\u5b9a",click:function(){$(this).dialog("close")}}]});
$("#filteryearbutton").click(function(){$("#filteryearwindow").dialog("open")});$("#filterclasswindow").dialog({title:"\u904e\u6ffe\u985e\u5225",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0,position:{my:"top",at:"bottom",of:$("#filterclassbutton")},buttons:[{text:"\u5168\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!0);hideunfittingprojects(b)}},{text:"\u5168\u4e0d\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!1);hideunfittingprojects(b)}},
{text:"\u78ba\u5b9a",click:function(){$(this).dialog("close")}}]});$("#filterclassbutton").click(function(){$("#filterclasswindow").dialog("open")});$("#filterplatformwindow").dialog({title:"\u904e\u6ffe\u5e73\u53f0",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0,position:{my:"top",at:"bottom",of:$("#filterplatformbutton")},buttons:[{text:"\u5168\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!0);hideunfittingprojects(b)}},{text:"\u5168\u4e0d\u9078",click:function(){$(this).find(".filtercheck").prop("checked",
!1);hideunfittingprojects(b)}},{text:"\u78ba\u5b9a",click:function(){$(this).dialog("close")}}]});$("#filterplatformbutton").click(function(){$("#filterplatformwindow").dialog("open")});sortwithfunction(sortwithid,b,!1);$(".sortcontrol").click(function(){sortprojects($(this),b)});loadColumnSelection("#columnselectwindow","#projecttable");$("#columnselectwindow").dialog({title:"\u9078\u64c7\u986f\u793a\u6b04\u4f4d",height:"auto",width:"auto",autoOpen:!1,draggable:!1,modal:!0,position:{my:"top",at:"bottom",
of:$("#selectcolumnbutton")},buttons:[{text:"\u5168\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!0);hideColumns()}},{text:"\u5168\u4e0d\u9078",click:function(){$(this).find(".filtercheck").prop("checked",!1);hideColumns()}},{text:"\u78ba\u5b9a",click:function(){$(this).dialog("close")}}]})});
function loadColumnSelection(b,a){$(b).empty();$(a+" th").each(function(){$(b).append('<input type="checkbox" class="filtercheck" value='+($(this).index()+1)+" checked>"+$(this).text()+"</input>")});$(b).find(".filtercheck").change(function(){hideColumns()})}function selectColumn(){$("#columnselectwindow").dialog("open")}
function hideColumns(){$("#columnselectwindow").find(".filtercheck").each(function(){var b=$(this).prop("checked"),a=$(this).val();b?$("#projecttable th:nth-child("+a+"),#projecttable td:nth-child("+a+")").show():$("#projecttable th:nth-child("+a+"),#projecttable td:nth-child("+a+")").hide()})};
